const STORAGE_NAME = "@maosentrelacadas";

const COLLECTION_INTRODUCTION = `${STORAGE_NAME}:introduction`;
const COLLECTION_USER = `${STORAGE_NAME}:user`;
const COLLECTION_THEME = `${STORAGE_NAME}:theme`;
const COLLECTION_FONT_SIZE = `${STORAGE_NAME}:font-size`;

export {
  COLLECTION_INTRODUCTION,
  COLLECTION_USER,
  COLLECTION_THEME,
  COLLECTION_FONT_SIZE,
};
