const STORAGE_NAME = "@maosentrelacadas";

const COLLECTION_INTRODUCTION = `${STORAGE_NAME}:introduction`;
const COLLECTION_USER = `${STORAGE_NAME}:user`;
const COLLECTION_THEME = `${STORAGE_NAME}:theme`;

export { COLLECTION_INTRODUCTION, COLLECTION_USER, COLLECTION_THEME };
